### ISSUE TITLE
Adding dropdown list

### ISSUE THREAD

**Issue by DooorisXu** [MLavrentyev/TeamManager#31]
Adding a dropdown list for the categories of the product in the request page.
Categories are:
- Office Supplies 
- Marketing and Spirit 
- Parts and Components of Robot
- Shop Supplies 
- Other 

This will be a required field and this information should be included in the email as well.  
This dropdown list is preferred to be positioned under the line for item name.

**Comment by MLavrentyev** [comment]
Will require some thought on how to do a migration if it is to be required, since the rows that already exist in the database don't have that field.

Need to research but will possibly need two migrations - first by adding it as an optional field, then going and manually adding the categories to each row, then by migrating it to a required field. I'll check to see if this works in the development server first, though.

**Comment by DooorisXu** [comment]
The purpose of having this feature is to make CAW at the end of build season quicker and better.  It'd be a great thing to have but it is not at a make or break level of importance.

**Comment by MLavrentyev** [comment]
I'm going to start working on this now; here's the plan:
- Add a dropdown select box to the new and edit pages
- Add the categories to `settings.py` so teams can set them before deploying*
- Allow filtering by category by using the syntax `cat:<category>` (e.g "cat:marketing")
- Add this field to the exported csv

Is there anything I'm missing @DooorisXu?

* I'm going to later add a settings page so these things can be set from the site itself (by mentors/admins)
